#!/bin/sh

#sh SetupProgram to run in Desktop directory

#this downloads any available updates to make sure we have the most current version
sudo apt update
sudo apt upgrade -y

#installs python, apache, and flask
sudo apt install python3
sudo apt install apache2 -y
sudo apt install time
sudo pip3 install flask
sudo apt-get install python3-pandas -y
sudo pip3 install openpyxl==2.6.4
sudo pip3 install mariadb

#installs a fork of MySQL, called maria data base and a python accessible api
sudo apt install mariadb-server -y
sudo apt install mariadb -y

#makes the preparations for and deploys app.py
cd /home/pi
mkdir webapp
cd webapp
mkdir templates
cd /home/pi/webapp
mv /home/pi/Desktop/app.py /home/pi/webapp/
mv /home/pi/Desktop/index.html /home/pi/webapp/templates/
python3 app.py
cd /home/pi/Desktop

#installs the excel sheet for the dividend stocks
wget https://bit.ly/USDividendChampions1
mv USDividendChampions1 USDividendChampions1.xlsx
mv ServerSetup ServerSetup.sql

