#!/bin/sh

#sh SetupProgram to run in Desktop directory

#this downloads any available updates to make sure we have the most current version
sudo apt update
sudo apt upgrade -y

#installs python, apache, and flask
sudo apt install python3
sudo apt-get install -y python3-pip
sudo apt install apache2 -y
sudo apt install time
sudo pip3 install flask
sudo pip3 install openpyxl==2.6.4
sudo apt-get install python3.6-dev libmysqlclient-dev
sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
curl -LsS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
sudo apt-get install -y apt-transport-https
sudo apt-get update
sudo apt-get upgrade
sudo apt install mariadb-server -y
sudo apt install mariadb -y
sudo apt install mysql-client-core-5.7
sudo apt-get install mysql-server -y
sudo apt-get dist-upgrade
sudo apt-get install -y mysql-server=8.0
sudo apt-get install libmariadb3
sudo apt-get install libmariadb-dev
sudo apt-get install libapache2-mod-wsgi-py3
sudo pip3 install mariadb
sudo pip3 install matplotlib
sudo pip3 install mysql-connector

#installs the excel sheet for the dividend stocks
wget https://bit.ly/USDividendChampions1
mv USDividendChampions1 USDividendChampions.xlsx
mv ServerSetup ServerSetup.sql

#makes the preparations for and deploys app.py
cd /home/ubuntu/RaspberryPiScripts/Website
mkdir webapp
cd webapp
mkdir templates
cd /home/ubuntu/RaspberryPiScripts/Website
mv /home/ubuntu/RaspberryPiScripts/Website/app.py /home/ubuntu/RaspberryPiScripts/Website/webapp
mv /home/ubuntu/RaspberryPiScripts/Website/index.html /home/ubuntu/RaspberryPiScripts/Website/webapp/templates
mv /home/ubuntu/RaspberryPiScripts/Website/stockgraph.html /home/ubuntu/RaspberryPiScripts/Website/webapp/templates/
#python3 app.py
cd /home/ubuntu/RaspberryPiScripts
